const cardsDataBrown = [
  {
    id: "brown1",
    cardFace: "./images/img/Mistic_cards/Brown/brown1.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown2",
    cardFace: "./images/img/Mistic_cards/Brown/brown2.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown3",
    cardFace: "./images/img/Mistic_cards/Brown/brown3.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown4",
    cardFace: "./images/img/Mistic_cards/Brown/brown4.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown5",
    cardFace: "./images/img/Mistic_cards/Brown/brown5.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown6",
    cardFace: "./images/img/Mistic_cards/Brown/brown6.png",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown7",
    cardFace: "./images/img/Mistic_cards/Brown/brown7.png",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown8",
    cardFace: "./images/img/Mistic_cards/Brown/brown8.png",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown9",
    cardFace: "./images/img/Mistic_cards/Brown/brown9.png",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown10",
    cardFace: "./images/img/Mistic_cards/Brown/brown10.png",
    difficulty: "hard",
    color: "brown",
  },
  {
    id: "brown11",
    cardFace: "./images/img/Mistic_cards/Brown/brown11.png",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown12",
    cardFace: "./images/img/Mistic_cards/Brown/brown12.png",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown13",
    cardFace: "./images/img/Mistic_cards/Brown/brown13.png",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown14",
    cardFace: "./images/img/Mistic_cards/Brown/brown14.png",
    difficulty: "easy",
    color: "brown",
  },
  {
    id: "brown15",
    cardFace: "./images/img/Mistic_cards/Brown/brown15.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown16",
    cardFace: "./images/img/Mistic_cards/Brown/brown16.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown17",
    cardFace: "./images/img/Mistic_cards/Brown/brown17.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown18",
    cardFace: "./images/img/Mistic_cards/Brown/brown18.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown19",
    cardFace: "./images/img/Mistic_cards/Brown/brown19.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown20",
    cardFace: "./images/img/Mistic_cards/Brown/brown20.png",
    difficulty: "normal",
    color: "brown",
  },
  {
    id: "brown21",
    cardFace: "./images/img/Mistic_cards/Brown/brown21.png",
    difficulty: "easy",
    color: "brown",
  },
];

export { cardsDataBrown };
